#!/usr/bin/env bash
#
# Usage: %fullSub% sub commands
#
# Summary: List all `%fullSub% sub` commands
#
# Help: This command is mostly used for autocompletion in various shells, and
# for `%fullSub% sub help`.
#
set -e

# Provide autocompletions
if [ "$1" = "--complete" ]; then
  echo --sh
  echo --no-sh
  exit
fi

if [ "$1" == "--sh" ]; then
  sh=1
  shift
elif [ "$1" == "--no-sh" ]; then
  nosh=1
  shift
fi

shopt -s nullglob

# Include all commands that exist in libexec
{ for command in "${_CUR_ROOT}/libexec/"*; do
    command="${command##*libexec/}"
    if [ ${sh:-0} -eq 1 ]; then
      [ ${command:0:3}  = "sh-" ] && echo ${command##sh-}
    elif [ ${nosh:-0} -eq 1 ]; then
      [ ${command:0:3} != "sh-" ] && echo ${command##sh-}
    else
      echo "${command##sh-}"
    fi
  done
} | sort | uniq
