#!/usr/bin/env bash
#
# Provide shell initialization to allow this sub to be used within the current
# shell session, including autocompletion.
#
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi

shell="$1"
[ -z "$shell" ] && shell="$(basename "$SHELL")"

if [ -z "$print" ]; then
  case "$shell" in
    bash ) profile='~/.bash_profile' ;;
    zsh )  profile='~/.zshenv' ;;
    * )    profile='your profile' ;;
  esac

  { echo "# Load %sub% automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_CUR_ROOT}/bin/%sub% init -)\""
    echo
  } >&2

  exit 1
fi

echo "export PATH=\"\${PATH}:${_CUR_ROOT}/bin\""

case "$shell" in
  bash | zsh ) echo "source \"$root/completions/sub.${shell}\"" ;;
esac
