#!/usr/bin/env bash
set -e

# Include the global utilities
source "$(cd "$(dirname "$0")/.." && pwd -P)/lib/utils.sh"

libexec="$(abs_dirname "$0")"
export _SUB_ROOT="$(abs_dirname "$libexec")"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec "${libexec}/help"
  ;;
* )
  command_path="${libexec}/$command"
  if [[ $command_path != true && -d "$command_path" ]]; then
    command_path="${command_path}/bin/$command"
  fi
  if [ ! -x "$command_path" ]; then
    echo "sub: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
